[workspace]

members = ["luanti-protocol", "luanti-protocol-derive", "luanti-shark"]

[profile.dev]
panic = "unwind"
opt-level = 0
debug = true
strip = "none"

[profile.test]
panic = 'abort'

[profile.bench]
panic = 'abort'

[profile.release]
panic = 'abort'
