use luanti_protocol::commands::{
    client_to_server::{
        DamageSpec, InteractSpec, InventoryActionSpec, InventoryFieldsSpec, ModchannelJoinSpec,
        ModchannelLeaveSpec, NodemetaFieldsSpec, PlayerItemSpec, PlayerPosCommand, RespawnSpec,
        TSChatMessageSpec, TSModchannelMsgSpec,
    },
    server_to_client::{
        AcceptSudoModeSpec, AccessDeniedCommand, ActiveObjectMessagesCommand,
        ActiveObjectRemoveAddSpec, AddParticlespawnerCommand, AddnodeSpec, AnnounceMediaSpec,
        AuthAcceptSpec, BreathSpec, CloudParamsSpec, CsmRestrictionFlagsSpec, DeathscreenSpec,
        DeleteParticlespawnerSpec, DenySudoModeSpec, DetachedInventorySpec, EyeOffsetSpec,
        FadeSoundSpec, FormspecPrependSpec, FovSpec, HelloSpec, HpSpec, InventoryFormspecSpec,
        InventorySpec, ItemdefCommand, LocalPlayerAnimationsSpec, MediaPushSpec, MinimapModesSpec,
        ModchannelSignalSpec, MovePlayerSpec, MovementSpec, NodedefSpec, NodemetaChangedSpec,
        OverrideDayNightRatioSpec, PlaySoundSpec, PlayerSpeedSpec, PrivilegesSpec, RemovenodeSpec,
        SetLightingSpec, SetMoonSpec, SetSkyCommand, SetStarsSpec, SetSunSpec, ShowFormspecSpec,
        SpawnParticleCommand, SrpBytesSBSpec, StopSoundSpec, TCChatMessageSpec,
        TCModchannelMsgSpec, TimeOfDaySpec, UpdatePlayerListSpec,
    },
};

#[derive(Debug)]
pub enum ToPluginEvent {
    ModchannelJoin(ModchannelJoinSpec),
    ModchannelLeave(ModchannelLeaveSpec),
    TSModchannelMsg(TSModchannelMsgSpec),
    Playerpos(PlayerPosCommand),
    InventoryAction(InventoryActionSpec),
    TSChatMessage(TSChatMessageSpec),
    Damage(DamageSpec),
    PlayerItem(PlayerItemSpec),
    Respawn(RespawnSpec),
    Interact(InteractSpec),
    NodemetaFields(NodemetaFieldsSpec),
    InventoryFields(InventoryFieldsSpec),
}

#[derive(Debug)]
pub enum FromPluginEvent {
    Hello(HelloSpec),
    AuthAccept(AuthAcceptSpec),
    AcceptSudoMode(AcceptSudoModeSpec),
    DenySudoMode(DenySudoModeSpec),
    AccessDenied(AccessDeniedCommand),
    Addnode(AddnodeSpec),
    Removenode(RemovenodeSpec),
    Inventory(InventorySpec),
    TimeOfDay(TimeOfDaySpec),
    CsmRestrictionFlags(CsmRestrictionFlagsSpec),
    PlayerSpeed(PlayerSpeedSpec),
    MediaPush(MediaPushSpec),
    TCChatMessage(TCChatMessageSpec),
    ActiveObjectRemoveAdd(ActiveObjectRemoveAddSpec),
    ActiveObjectMessages(ActiveObjectMessagesCommand),
    Hp(HpSpec),
    MovePlayer(MovePlayerSpec),
    // AccessDeniedLegacy(AccessDeniedLegacySpec),
    Fov(FovSpec),
    Deathscreen(DeathscreenSpec),
    Nodedef(NodedefSpec),
    AnnounceMedia(AnnounceMediaSpec),
    Itemdef(ItemdefCommand),
    PlaySound(PlaySoundSpec),
    StopSound(StopSoundSpec),
    Privileges(PrivilegesSpec),
    InventoryFormspec(InventoryFormspecSpec),
    DetachedInventory(DetachedInventorySpec),
    ShowFormspec(ShowFormspecSpec),
    Movement(MovementSpec),
    SpawnParticle(SpawnParticleCommand),
    AddParticlespawner(Box<AddParticlespawnerCommand>),
    Breath(BreathSpec),
    SetSky(SetSkyCommand),
    OverrideDayNightRatio(OverrideDayNightRatioSpec),
    LocalPlayerAnimations(LocalPlayerAnimationsSpec),
    EyeOffset(EyeOffsetSpec),
    DeleteParticlespawner(DeleteParticlespawnerSpec),
    CloudParams(CloudParamsSpec),
    FadeSound(FadeSoundSpec),
    UpdatePlayerList(UpdatePlayerListSpec),
    TCModchannelMsg(TCModchannelMsgSpec),
    ModchannelSignal(ModchannelSignalSpec),
    NodemetaChanged(NodemetaChangedSpec),
    SetSun(SetSunSpec),
    SetMoon(SetMoonSpec),
    SetStars(SetStarsSpec),
    SrpBytesSB(SrpBytesSBSpec),
    FormspecPrepend(FormspecPrependSpec),
    MinimapModes(MinimapModesSpec),
    SetLighting(SetLightingSpec),
}
