[package]
name = "luanti-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
glam.workspace = true

[lints]
workspace = true
